import = ["/home/nick/.config/alacritty/themes/catppuccin-mocha.toml"]

[cursor]
style = "Block"

[font]
size = 10.0

[font.bold]
family = "JetBrains Mono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NF"
style = "Italic"

[font.normal]
family = "JetBrains Mono NF"
style = "Regular"

[window]
opacity = 0.95
