#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width	2
bspc config window_gap		12

bspc config split_ratio		0.52
bspc config borderless_monocle  true
bspc config gapless_monocle	true

# colors
bspc config active_border_color \#230094
bspc config normal_border_color \#675d87

# fix cursor issue
xsetroot -cursor_name left_ptr &

# set the wallpaper
feh --bg-fill ~/.config/wallpaper/wall.png

# start polybar
~/.config/polybar/launch.sh --blocks
